include: package:lints/recommended.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    hash_and_equals: true
    prefer_void_to_null: true
    test_types_in_equals: true
    unnecessary_statements: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    empty_catches: true
    empty_constructor_bodies: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    sized_box_for_whitespace: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_late: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    library_private_types_in_public_api: false
    use_build_context_synchronously: false

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/localization/l10n/generated/*
    - lib/**.g.dart

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-redundant-async
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - no-equal-then-else
    - avoid-passing-async-when-sync-expected: false
