name: core
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0

  mobx: 2.5.0
  flutter_mobx: 2.3.0

dev_dependencies:
  flutter_lints: 5.0.0
  dart_code_metrics_presets: 2.20.0
