name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0

  provider: 6.1.2
  get_it: 8.0.3
  
  go_router: 14.6.3
  
  shared_preferences: 2.3.5
  hive: 4.0.0-dev.2
  isar_flutter_libs: 4.0.0-dev.14
  path_provider: 2.1.5

  collection: 1.19.0
  equatable: 2.0.7

  flutter_blue_plus: 1.34.5
  app_settings: 5.1.1

  lottie: 3.3.1

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  dart_code_metrics_presets: 2.20.0
  build_runner: 2.4.14
  mobx_codegen: 2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/
  fonts:
    - family: SFUIText
      fonts:
        - asset: packages/core_ui/assets/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: packages/core_ui/assets/fonts/SFUIText-Heavy.ttf
          weight: 800
        - asset: packages/core_ui/assets/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: packages/core_ui/assets/fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: packages/core_ui/assets/fonts/SFUIText-Regular.ttf
          weight: 400
          style: normal
        - asset: packages/core_ui/assets/fonts/SFUIText-Light.ttf
          weight: 300
        - asset: packages/core_ui/assets/fonts/SFUIText-UltraLight.ttf
          weight: 200
    - family: Papillon
      fonts:
        - asset: packages/core_ui/assets/fonts/Papillon.ttf
          weight: 400
          style: normal
    - family: CoreUIIcons
      fonts:
        - asset: packages/core_ui/assets/fonts/CoreUIIcons.otf
