name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: 6.1.2
  get_it: 7.6.7
  
  go_router: 14.2.9
  
  shared_preferences: 2.2.2

  collection: 1.18.0
  equatable: 2.0.5

  flutter_blue_plus: 1.32.12

  core:
    path: ../core
  ui_core:
    path: ../ui_core
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  dart_code_metrics_presets: 2.10.0
  build_runner: 2.4.8
  mobx_codegen: 2.6.1

flutter:
  uses-material-design: true
  fonts:
    - family: SFUIText
      fonts:
        - asset: packages/ui_core/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: packages/ui_core/fonts/SFUIText-Heavy.ttf
          weight: 800
        - asset: packages/ui_core/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: packages/ui_core/fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: packages/ui_core/fonts/SFUIText-Regular.ttf
          weight: 400
          style: normal
        - asset: packages/ui_core/fonts/SFUIText-Light.ttf
          weight: 300
        - asset: packages/ui_core/fonts/SFUIText-UltraLight.ttf
          weight: 200
