preferred-supported-locales: [en, ru]
synthetic-package: false
output-dir: ./lib/localization/l10n/generated
arb-dir: ./lib/localization/l10n
template-arb-file: localization_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
