name: ui_core
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  
  shared_preferences: 2.2.2

dev_dependencies:
  flutter_lints: 3.0.0
  dart_code_metrics_presets: 2.10.0

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
