name: ui_core
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 6.1.2
  
  shared_preferences: 2.2.2

  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.8
  flutter_lints: 3.0.0
  dart_code_metrics_presets: 2.10.0
  mobx_codegen: 2.6.1

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
