name: core_ui
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0

  provider: 6.1.2
  
  shared_preferences: 2.3.5

  mobx: 2.5.0
  flutter_mobx: 2.3.0

dev_dependencies:
  flutter_lints: 5.0.0
  dart_code_metrics_presets: 2.20.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: SFUIText
      fonts:
        - asset: lib/assets/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/SFUIText-Heavy.ttf
          weight: 800
        - asset: lib/assets/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: lib/assets/fonts/SFUIText-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/SFUIText-Regular.ttf
          weight: 400
          style: normal
        - asset: lib/assets/fonts/SFUIText-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/SFUIText-UltraLight.ttf
          weight: 200
